---
# These tasks are deprecated
# Use suzuki-shunsuke.docker-ubuntu instead

  - name: Remove any existing Docker installations
    apt:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - docker.io
      - docker-engine

  - name: add aufs support
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - linux-image-extra-{{ ansible_kernel }}
      - linux-image-extra-virtual

  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Install Docker's official GPG key
    apt_key:
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      keyserver: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: HTTPS APT transport for Docker repository
    apt:
      name: apt-transport-https
      state: present

  - name: Add Docker repository and update apt cache
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_lsb.codename|lower }} stable"
      mode: 644
      update_cache: yes
      state: present

  - name: Install the latest version of Docker CE
    apt:
      name: docker-ce
      state: latest
