---
  - name: Add the torproject keys
    apt_key:
      keyserver: 'keys.gnupg.net'
      id: 'A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89'

  - name: Add outside repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items: "{{ apt_repos }}"

  - name: apt-update
    apt:
      update_cache: yes

  - name: Install some of my favorite softwares
    apt:
      name: "{{ item }}"
      state: latest
    with_items: "{{ apt_install_packages }}"

  - name: Remove softwares I don't need and purge their config files
    apt:
      name: "{{ item }}"
      state: absent
      purge: yes
    with_items: "{{ apt_purge_packages }}"

  - name: Autoremove unnecessary packages
    apt:
      autoremove: yes

  # Deprecated. Use gantsign.atom instead
  # - name: Install Atom v{{ atom_version }}
  #   apt:
  #     deb: https://github.com/atom/atom/releases/download/v{{ atom_version }}/atom-amd64.deb
