---
apt_install_packages:
                        - chromium-browser
                        - git
                        - terminator
                        - vlc
                        - vim
                        - ttf-anonymous-pro


apt_purge_packages:
                        - firefox
                        - thunderbird
                        - pidgin
                        - parole
                        - libreoffice*

# The version number of Atom.
atom_version: 1.19.2
